### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by bbendolph** [fywk/rfid-volumio#2]
I'm not sure what im doing wrong, but i get permission denied when doing step 1 to boot user config. Then on step 3, im not sure how to run read.py. I ran a similar program using talaexe's spotify rfid player. But when i boot up my volumio pi, the volumio player shows up, not the normal PI Linux. Any tips/help?

**Comment by fywk** [comment]
@bbendolph 

- What do you mean by boot user config? Step 1 is to add the line `dtparam-spi-on` to your `/boot/userconfig.txt` file. You can use the `nano` text editor to do it even if the file has not existed yet.

```bash
nano /boot/userconfig.txt
```

- For step 3, you first need to be in the `rfid-volumio` working directory and then run a utility program to read the details of your rfid cards with `python3 utils/read.py`. Make sure you have installed all the packages required in step 2. Keep in mind that this step just allows you to read the details of your empty rfid cards so that you can insert the IDs of those cards in the CSV file that you'll be creating in step 5.

```bash
# Assuming you're in the root directory
cd rfid-volumio
python3 utils/read.py
```

- Volumio is itself another Linux-based operating system, so that's why you'd see Volumio's UI when you boot your system up. 
- I checked out [talaexe/Spotify-RFID-Record-Player](https://github.com/talaexe/Spotify-RFID-Record-Player), and I assumed they were running their application in the standard Raspberry Pi OS. 
- You can run talaexe's application in Volumio OS too, as it just runs headlessly in the background.

**Comment by bbendolph** [comment]
I guess my problem is I don't really understand the difference between Volumios UI and the "normal Linux" PI UI, and how to run things like the read.py in the bakground or even get them to the Volumio Pi. I ran the spotify one on a separate SD card as a test.

**Comment by fywk** [comment]
May I know your setup currently?

**Comment by bbendolph** [comment]
Current setup is a pi with the 7 in touchscreen display, and an MFRC522 reader. THe pi OS SD card in the system now is base Volumio flashed. The other SD card not in the pi is the standard pi linux with tala's programs on it

**Comment by fywk** [comment]
Do you have access to the command line of Volumio?

**Comment by bbendolph** [comment]
I believe so, using SSH(?) and also on initial boot up

**Comment by fywk** [comment]
Great. Then what seems to be the problem?

You mentioned:
> ...how to run things like the read.py in the background.

You only need to run `read.py` when you want to read the id of your cards. Once the id is known, you can exit the script.

Here's the flow of how :

1. Scan your rfid card with `read.py` (only run this to get to know the id of your card)
2. Copy the id of the card from the output
3. Use the id that you've just acquired and paste it inside the playback.csv` file
4. Associate the id with a valid playback URI

So let's say you have a card with an ID of `000000000000`, and you want this card to play BBC Radio 2 every time you scan it. The following configuration in `playback.csv` would do just that.

```csv
ID,Service,URI,Name,Type
000000000000,webradio,http://stream.live.vc.bbcmedia.co.uk/bbc_radio_two,BBC Radio Two,Web Radio
```

**Comment by fywk** [comment]
I'm closing this for now. Feel free to ping me if you have any questions :)
